// This file is auto-generated by @hey-api/openapi-ts

export type AgentChatRequest = {
    question: string;
    top_k?: number;
    max_steps?: number;
    semantic_weight?: number;
    keyword_weight?: number;
};

export type AgentChatResponse = {
    agent_run_id?: (string | null);
    answer: string;
    tool_calls: Array<AgentToolCallPublic>;
    sources: Array<RagChatSource>;
    trace: Array<(string)>;
    latency_ms?: (number | null);
};

export type AgentRunPublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    question: string;
    answer: string;
    top_k: number;
    max_steps: number;
    semantic_weight: number;
    keyword_weight: number;
    latency_ms?: (number | null);
    tool_calls?: Array<AgentToolCallPublic>;
    sources?: Array<RagChatSource>;
    trace?: Array<(string)>;
    error_message?: (string | null);
    created_at?: (string | null);
};

export type AgentRunsPublic = {
    data: Array<AgentRunPublic>;
    count: number;
};

export type AgentToolCallPublic = {
    tool_name: string;
    arguments?: {
        [key: string]: unknown;
    };
    observation: string;
    success?: boolean;
};

export type Body_documents_upload_document = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_upload_code_repository_zip = {
    file: string;
};

export type CodeAgentExperimentReportPublic = {
    filename: string;
    mime_type?: string;
    content: string;
};

export type CodeEvalTypeCompareStat = {
    case_type: string;
    case_type_label: string;
    total_cases?: number;
    compared_cases?: number;
    rag_source_hit_rate?: number;
    agent_source_hit_rate?: number;
    rag_keyword_hit_rate?: number;
    agent_keyword_hit_rate?: number;
    rag_avg_latency_ms?: (number | null);
    agent_avg_latency_ms?: (number | null);
    agent_avg_tool_calls?: (number | null);
    agent_tool_usage_json?: (string | null);
};

export type CodeEvalTypeCompareSummaryPublic = {
    data: Array<CodeEvalTypeCompareStat>;
    count: number;
};

export type CodeReviewCompareFindingPublic = {
    fingerprint: string;
    title: string;
    severity?: (string | null);
    category?: (string | null);
    description?: (string | null);
    recommendation?: (string | null);
};

export type CodeReviewCompareRequest = {
    base_review_run_id: string;
    target_review_run_id: string;
};

export type CodeReviewCompareResponse = {
    base_review: CodeReviewRunCompareReferencePublic;
    target_review: CodeReviewRunCompareReferencePublic;
    overall_change: CodeReviewOverallChangePublic;
    metric_changes: CodeReviewMetricChangesPublic;
    finding_changes: CodeReviewFindingChangesPublic;
    test_changes: CodeReviewTestChangesPublic;
    trace_changes: CodeReviewTraceChangesPublic;
};

export type CodeReviewCompareTestPublic = {
    fingerprint: string;
    title: string;
    test_type?: (string | null);
    file_path?: (string | null);
    reason?: (string | null);
};

export type CodeReviewFindingChangesPublic = {
    added?: Array<CodeReviewCompareFindingPublic>;
    resolved?: Array<CodeReviewCompareFindingPublic>;
    persisting?: Array<CodeReviewCompareFindingPublic>;
};

export type CodeReviewMetricChangePublic = {
    base_value: number;
    target_value: number;
    delta: number;
    trend: 'increased' | 'decreased' | 'unchanged';
};

export type trend = 'increased' | 'decreased' | 'unchanged';

export type CodeReviewMetricChangesPublic = {
    changed_file_count: CodeReviewMetricChangePublic;
    changed_symbol_count: CodeReviewMetricChangePublic;
    finding_count: CodeReviewMetricChangePublic;
    recommended_test_count: CodeReviewMetricChangePublic;
};

export type CodeReviewOverallChangePublic = {
    same_diff: boolean;
    risk: CodeReviewValueChangePublic;
    merge_recommendation: CodeReviewValueChangePublic;
    generation_status: CodeReviewValueChangePublic;
    summary: string;
};

export type CodeReviewPublicationPublic = {
    id: string;
    knowledge_base_id: string;
    review_run_id: string;
    provider: string;
    publication_type: string;
    requested_event: string;
    status: string;
    target_repository: string;
    target_change_number: number;
    target_head_sha: string;
    target_source_url: string;
    attempt_number: number;
    force_republish: boolean;
    body_hash: string;
    external_review_id?: (string | null);
    external_review_url?: (string | null);
    external_review_state?: (string | null);
    external_actor?: (string | null);
    error_code?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    published_at?: (string | null);
};

export type CodeReviewPublicationsPublic = {
    data: Array<CodeReviewPublicationPublic>;
    count: number;
};

export type CodeReviewRunCompareReferencePublic = {
    id: string;
    title: string;
    created_at: string;
    generation_status: 'completed' | 'evidence_only';
    risk_level?: ('low' | 'medium' | 'high' | null);
    merge_recommendation?: ('approve' | 'needs_review' | 'request_changes' | null);
    diff_hash: string;
};

export type generation_status = 'completed' | 'evidence_only';

export type CodeReviewRunDetailPublic = {
    id: string;
    knowledge_base_id: string;
    title: string;
    generation_status: 'completed' | 'evidence_only';
    language: string;
    risk_level?: ('low' | 'medium' | 'high' | null);
    merge_recommendation?: ('approve' | 'needs_review' | 'request_changes' | null);
    changed_file_count: number;
    changed_symbol_count: number;
    finding_count: number;
    recommended_test_count: number;
    created_at: string;
    source?: (CodeReviewSourceSnapshot | null);
    diff_text: string;
    diff_hash: string;
    request_parameters: {
        [key: string]: unknown;
    };
    review_report?: (CodeSkillGeneratedReviewReportPublic | null);
    review_markdown?: (string | null);
    evidence: CodeSkillReviewEvidenceResponse;
    generation_trace: CodeSkillReportGenerationTracePublic;
    generation_error?: (string | null);
};

export type CodeReviewRunsPublic = {
    data: Array<CodeReviewRunSummaryPublic>;
    count: number;
};

export type CodeReviewRunSummaryPublic = {
    id: string;
    knowledge_base_id: string;
    title: string;
    generation_status: 'completed' | 'evidence_only';
    language: string;
    risk_level?: ('low' | 'medium' | 'high' | null);
    merge_recommendation?: ('approve' | 'needs_review' | 'request_changes' | null);
    changed_file_count: number;
    changed_symbol_count: number;
    finding_count: number;
    recommended_test_count: number;
    created_at: string;
    source?: (CodeReviewSourceSnapshot | null);
};

export type CodeReviewSourceResolvedPublic = {
    provider: 'github' | 'gitlab';
    source_url: string;
    repository: string;
    change_number: number;
    title: string;
    author?: (string | null);
    base_ref: string;
    head_ref: string;
    base_sha: string;
    head_sha: string;
    diff_hash: string;
    fetched_at: string;
    diff_text: string;
};

export type provider = 'github' | 'gitlab';

export type CodeReviewSourceResolveRequest = {
    source_url: string;
};

export type CodeReviewSourceSnapshot = {
    provider: 'github' | 'gitlab';
    source_url: string;
    repository: string;
    change_number: number;
    title: string;
    author?: (string | null);
    base_ref: string;
    head_ref: string;
    base_sha: string;
    head_sha: string;
    diff_hash: string;
    fetched_at: string;
};

export type CodeReviewTestChangesPublic = {
    added?: Array<CodeReviewCompareTestPublic>;
    removed?: Array<CodeReviewCompareTestPublic>;
    persisting?: Array<CodeReviewCompareTestPublic>;
};

export type CodeReviewTraceChangesPublic = {
    model: CodeReviewValueChangePublic;
    duration_ms?: (CodeReviewMetricChangePublic | null);
    evidence_item_count?: (CodeReviewMetricChangePublic | null);
    output_characters?: (CodeReviewMetricChangePublic | null);
};

export type CodeReviewValueChangePublic = {
    base_value?: (string | null);
    target_value?: (string | null);
    trend: 'increased' | 'decreased' | 'unchanged' | 'changed' | 'unavailable';
};

export type trend2 = 'increased' | 'decreased' | 'unchanged' | 'changed' | 'unavailable';

export type CodeSkillBuildReviewEvidenceRequest = {
    diff_text: string;
    max_references_per_symbol?: number;
    max_test_files?: number;
    min_test_confidence?: number;
    include_file_level_fallback?: boolean;
    include_definition_chunk?: boolean;
};

export type CodeSkillChangedFilePublic = {
    old_path?: (string | null);
    new_path?: (string | null);
    file_path: string;
    change_type: string;
    added_lines?: number;
    deleted_lines?: number;
    hunks?: Array<CodeSkillDiffHunkPublic>;
};

export type CodeSkillChangedSymbolInput = {
    document_id?: (string | null);
    chunk_id?: (string | null);
    file_path: string;
    symbol_name: string;
    symbol_type?: string;
    line_range?: (string | null);
};

export type CodeSkillChangedSymbolPublic = {
    document_id?: (string | null);
    chunk_id?: (string | null);
    chunk_index?: (number | null);
    document_filename?: (string | null);
    file_path: string;
    symbol_name: string;
    symbol_type: string;
    line_range?: (string | null);
    symbol_start_line?: (number | null);
    symbol_end_line?: (number | null);
    changed_hunk_new_start: number;
    changed_hunk_new_end: number;
    overlap_start_line?: (number | null);
    overlap_end_line?: (number | null);
    overlap_line_count?: number;
    confidence?: number;
    reason: string;
};

export type CodeSkillChangeSummaryPublic = {
    total_changed_files?: number;
    total_added_lines?: number;
    total_deleted_lines?: number;
    total_changed_symbols?: number;
    total_unresolved_files?: number;
    total_references?: number;
    total_impacted_files?: number;
    total_test_candidates?: number;
    total_recommended_tests?: number;
    total_risk_signals?: number;
    risk_level?: string;
};

export type CodeSkillDiffHunkPublic = {
    old_start: number;
    old_count: number;
    new_start: number;
    new_count: number;
    added_lines?: number;
    deleted_lines?: number;
    context_lines?: number;
};

export type CodeSkillEvidenceTraceStepPublic = {
    step: string;
    status?: string;
    duration_ms?: number;
    summary: string;
};

export type CodeSkillFindImpactsRequest = {
    changed_symbols?: Array<CodeSkillChangedSymbolInput>;
    max_references_per_symbol?: number;
    include_definition_chunk?: boolean;
};

export type CodeSkillFindImpactsResponse = {
    symbol_impacts?: Array<CodeSkillSymbolImpactPublic>;
    impacted_files_summary?: Array<CodeSkillImpactedFilePublic>;
    total_symbols?: number;
    total_references?: number;
    total_impacted_files?: number;
};

export type CodeSkillGeneratedFindingPublic = {
    finding_id: string;
    severity: 'low' | 'medium' | 'high';
    category: string;
    title: string;
    description: string;
    recommendation: string;
    evidence_ids: Array<(string)>;
};

export type severity = 'low' | 'medium' | 'high';

export type CodeSkillGeneratedManualReviewItemPublic = {
    description: string;
    priority?: 'low' | 'medium' | 'high';
    evidence_ids: Array<(string)>;
};

export type priority = 'low' | 'medium' | 'high';

export type CodeSkillGeneratedOverallAssessmentPublic = {
    risk_level?: 'low' | 'medium' | 'high';
    conclusion: string;
    merge_recommendation?: 'approve' | 'needs_review' | 'request_changes';
};

export type risk_level = 'low' | 'medium' | 'high';

export type merge_recommendation = 'approve' | 'needs_review' | 'request_changes';

export type CodeSkillGeneratedReviewReportPublic = {
    executive_summary: string;
    overall_assessment: CodeSkillGeneratedOverallAssessmentPublic;
    findings?: Array<CodeSkillGeneratedFindingPublic>;
    test_plan?: Array<CodeSkillGeneratedTestPlanItemPublic>;
    manual_review_items?: Array<CodeSkillGeneratedManualReviewItemPublic>;
    uncertainties?: Array<(string)>;
};

export type CodeSkillGeneratedTestPlanItemPublic = {
    test_file: string;
    reason: string;
    priority?: 'low' | 'medium' | 'high';
    evidence_ids: Array<(string)>;
};

export type CodeSkillGenerateReviewReportRequest = {
    diff_text: string;
    max_references_per_symbol?: number;
    max_test_files?: number;
    min_test_confidence?: number;
    include_file_level_fallback?: boolean;
    include_definition_chunk?: boolean;
    language?: 'zh-CN' | 'en-US';
    source?: (CodeReviewSourceSnapshot | null);
};

export type language = 'zh-CN' | 'en-US';

export type CodeSkillGenerateReviewReportResponse = {
    generation_status: 'completed' | 'evidence_only';
    review_report?: (CodeSkillGeneratedReviewReportPublic | null);
    review_markdown?: (string | null);
    evidence: CodeSkillReviewEvidenceResponse;
    generation_trace: CodeSkillReportGenerationTracePublic;
    generation_error?: (string | null);
    review_run_id?: (string | null);
    saved_at?: (string | null);
};

export type CodeSkillImpactedFileInput = {
    file_path: string;
    reference_count?: number;
    impacted_symbol_names?: Array<(string)>;
};

export type CodeSkillImpactedFilePublic = {
    file_path: string;
    document_filename?: (string | null);
    reference_count?: number;
    impacted_symbol_names?: Array<(string)>;
    confidence?: number;
    reason: string;
};

export type CodeSkillImpactReferencePublic = {
    document_id: string;
    chunk_id: string;
    chunk_index: number;
    document_filename: string;
    file_path: string;
    changed_symbol_name: string;
    changed_symbol_type: string;
    containing_symbol_name?: (string | null);
    containing_symbol_type?: (string | null);
    containing_line_range?: (string | null);
    occurrence_count?: number;
    preview?: (string | null);
    confidence?: number;
    reason: string;
};

export type CodeSkillLocateChangedSymbolsRequest = {
    diff_text: string;
    include_file_level_fallback?: boolean;
};

export type CodeSkillLocateChangedSymbolsResponse = {
    changed_files?: Array<CodeSkillChangedFilePublic>;
    changed_symbols?: Array<CodeSkillChangedSymbolPublic>;
    unresolved_files?: Array<(string)>;
    total_files?: number;
    total_symbols?: number;
    total_unresolved_files?: number;
};

export type CodeSkillParseDiffRequest = {
    diff_text: string;
};

export type CodeSkillParseDiffResponse = {
    changed_files?: Array<CodeSkillChangedFilePublic>;
    total_files?: number;
    total_added_lines?: number;
    total_deleted_lines?: number;
};

export type CodeSkillRecommendedTestPublic = {
    document_id: string;
    document_filename: string;
    test_file_path: string;
    confidence?: number;
    path_match_score?: number;
    symbol_match_count?: number;
    related_changed_files?: Array<(string)>;
    related_impacted_files?: Array<(string)>;
    related_symbols?: Array<(string)>;
    matched_reasons?: Array<(string)>;
    preview?: (string | null);
};

export type CodeSkillRecommendTestsRequest = {
    changed_files?: Array<(string)>;
    changed_symbols?: Array<CodeSkillChangedSymbolInput>;
    impacted_files?: Array<CodeSkillImpactedFileInput>;
    max_test_files?: number;
    min_confidence?: number;
};

export type CodeSkillRecommendTestsResponse = {
    recommended_tests?: Array<CodeSkillRecommendedTestPublic>;
    test_gap_notes?: Array<(string)>;
    uncovered_changed_files?: Array<(string)>;
    uncovered_symbols?: Array<(string)>;
    total_test_candidates?: number;
    total_recommended_tests?: number;
    analysis_method?: string;
    limitations?: Array<(string)>;
};

export type CodeSkillReportGenerationTracePublic = {
    model: string;
    duration_ms?: number;
    prompt_version?: string;
    evidence_item_count?: number;
    output_characters?: number;
};

export type CodeSkillReviewChecklistItemPublic = {
    item_id: string;
    category: string;
    priority: string;
    description: string;
    reason: string;
    related_files?: Array<(string)>;
    related_symbols?: Array<(string)>;
};

export type CodeSkillReviewEvidenceResponse = {
    change_summary: CodeSkillChangeSummaryPublic;
    changed_files?: Array<CodeSkillChangedFilePublic>;
    changed_symbols?: Array<CodeSkillChangedSymbolPublic>;
    unresolved_files?: Array<(string)>;
    symbol_impacts?: Array<CodeSkillSymbolImpactPublic>;
    impacted_files_summary?: Array<CodeSkillImpactedFilePublic>;
    recommended_tests?: Array<CodeSkillRecommendedTestPublic>;
    test_gap_notes?: Array<(string)>;
    uncovered_changed_files?: Array<(string)>;
    uncovered_symbols?: Array<(string)>;
    risk_signals?: Array<CodeSkillRiskSignalPublic>;
    review_checklist?: Array<CodeSkillReviewChecklistItemPublic>;
    evidence_trace?: Array<CodeSkillEvidenceTraceStepPublic>;
    limitations?: Array<(string)>;
};

export type CodeSkillRiskSignalPublic = {
    risk_type: string;
    risk_level: string;
    title: string;
    message: string;
    evidence?: Array<(string)>;
    related_files?: Array<(string)>;
    related_symbols?: Array<(string)>;
};

export type CodeSkillSymbolImpactPublic = {
    changed_symbol: CodeSkillChangedSymbolInput;
    references?: Array<CodeSkillImpactReferencePublic>;
    impacted_files?: Array<CodeSkillImpactedFilePublic>;
    total_references?: number;
    total_impacted_files?: number;
};

export type DocumentChunkPublic = {
    chunk_index: number;
    content: string;
    content_length: number;
    id: string;
    document_id: string;
    knowledge_base_id: string;
    owner_id: string;
    embedding_model?: (string | null);
    embedding_status?: string;
    embedding_error?: (string | null);
    created_at?: (string | null);
};

export type DocumentChunksPublic = {
    data: Array<DocumentChunkPublic>;
    count: number;
};

export type DocumentPublic = {
    original_filename: string;
    content_type?: (string | null);
    file_size: number;
    status?: string;
    error_message?: (string | null);
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    filename: string;
    storage_path: string;
    created_at?: (string | null);
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type GitHubReviewPublicationPreviewPublic = {
    review_run_id: string;
    target_repository: string;
    target_change_number: number;
    target_source_url: string;
    reviewed_head_sha: string;
    default_event: string;
    allowed_events: Array<(string)>;
    already_published: boolean;
    successful_publication_count: number;
    latest_publication?: (CodeReviewPublicationPublic | null);
    body_markdown: string;
    body_hash: string;
    body_character_count: number;
};

/**
 * 用户确认发布时允许提交的字段。
 *
 * 仓库、PR、SHA 和正文全部从
 * CodeReviewRun 中读取，前端不能覆盖。
 */
export type GitHubReviewPublicationRequest = {
    event?: (string | null);
    force_republish?: boolean;
};

export type GitHubReviewPublicationResultPublic = {
    publication: CodeReviewPublicationPublic;
    requested_event: string;
    current_head_sha: string;
    pull_request_url: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KnowledgeBaseAgentSettingsPublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    top_k: number;
    max_steps: number;
    semantic_weight: number;
    keyword_weight: number;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type KnowledgeBaseAgentSettingsUpdate = {
    top_k?: (number | null);
    max_steps?: (number | null);
    semantic_weight?: (number | null);
    keyword_weight?: (number | null);
};

export type KnowledgeBaseCreate = {
    name: string;
    description?: (string | null);
};

export type KnowledgeBaseEmbeddingBackfillRequest = {
    limit?: number;
    retry_failed?: boolean;
    force?: boolean;
};

export type KnowledgeBaseEmbeddingBackfillResult = {
    model: string;
    processed: number;
    embedded: number;
    failed: number;
    remaining: number;
};

export type KnowledgeBasePublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type KnowledgeBaseSearchRequest = {
    query: string;
    limit?: number;
};

export type KnowledgeBaseSearchResult = {
    document_id: string;
    original_filename: string;
    chunk_id: string;
    chunk_index: number;
    content: string;
    content_length: number;
    match_count?: number;
};

export type KnowledgeBaseSearchResults = {
    data: Array<KnowledgeBaseSearchResult>;
    count: number;
};

export type KnowledgeBaseSemanticSearchRequest = {
    query: string;
    top_k?: number;
};

export type KnowledgeBaseSemanticSearchResult = {
    document_id: string;
    original_filename: string;
    chunk_id: string;
    chunk_index: number;
    content: string;
    content_length: number;
    similarity: number;
};

export type KnowledgeBaseSemanticSearchResults = {
    data: Array<KnowledgeBaseSemanticSearchResult>;
    count: number;
};

export type KnowledgeBasesPublic = {
    data: Array<KnowledgeBasePublic>;
    count: number;
};

export type KnowledgeBaseUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RagAgentCompareBatchDetailPublic = {
    batch: RagAgentCompareBatchPublic;
    data: Array<RagAgentCompareItemPublic>;
    count: number;
};

export type RagAgentCompareBatchesPublic = {
    data: Array<RagAgentCompareBatchPublic>;
    count: number;
};

export type RagAgentCompareBatchPublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    name: string;
    top_k: number;
    max_steps: number;
    limit: number;
    semantic_weight: number;
    keyword_weight: number;
    total_cases: number;
    ran: number;
    failed: number;
    average_rag_latency_ms?: (number | null);
    average_agent_latency_ms?: (number | null);
    average_rag_sources_count?: (number | null);
    average_agent_sources_count?: (number | null);
    average_agent_tool_call_count?: (number | null);
    total_agent_failed_tool_count: number;
    summarize_document_count: number;
    read_document_chunks_count: number;
    search_rag_history_count: number;
    created_at?: (string | null);
};

export type RagAgentCompareEvalItem = {
    eval_case_id: string;
    question: string;
    expected_keywords?: Array<(string)>;
    expected_source_filename?: (string | null);
    rag_answer?: (string | null);
    agent_answer?: (string | null);
    rag_latency_ms?: (number | null);
    agent_latency_ms?: (number | null);
    rag_sources_count?: number;
    agent_sources_count?: number;
    agent_tool_call_count?: number;
    agent_failed_tool_count?: number;
    agent_tool_names?: Array<(string)>;
    rag_sources?: Array<RagChatSource>;
    agent_sources?: Array<RagChatSource>;
    agent_tool_calls?: Array<AgentToolCallPublic>;
    rag_trace?: Array<(string)>;
    agent_trace?: Array<(string)>;
    rag_error_message?: (string | null);
    agent_error_message?: (string | null);
    is_failed?: boolean;
};

export type RagAgentCompareEvalRequest = {
    name?: (string | null);
    top_k?: number;
    max_steps?: number;
    limit?: number;
    semantic_weight?: number;
    keyword_weight?: number;
};

export type RagAgentCompareEvalResponse = {
    compare_batch_id?: (string | null);
    summary: RagAgentCompareEvalSummary;
    data: Array<RagAgentCompareEvalItem>;
    count: number;
};

export type RagAgentCompareEvalSummary = {
    total_cases?: number;
    ran?: number;
    failed?: number;
    average_rag_latency_ms?: (number | null);
    average_agent_latency_ms?: (number | null);
    average_rag_sources_count?: (number | null);
    average_agent_sources_count?: (number | null);
    average_agent_tool_call_count?: (number | null);
    total_agent_failed_tool_count?: number;
    summarize_document_count?: number;
    read_document_chunks_count?: number;
    search_rag_history_count?: number;
};

export type RagAgentCompareFailureAnalysisPublic = {
    total_items: number;
    failed_items: number;
    reason_stats: Array<RagAgentCompareFailureReasonStat>;
    data: Array<RagAgentCompareFailureCasePublic>;
    count: number;
};

export type RagAgentCompareFailureCasePublic = {
    id: string;
    batch_id: string;
    eval_case_id?: (string | null);
    question: string;
    case_type?: string;
    case_type_label?: string;
    failure_reasons?: Array<(string)>;
    failure_reason_labels?: Array<(string)>;
    rag_source_hit?: (boolean | null);
    agent_source_hit?: (boolean | null);
    rag_keyword_hit_rate?: number;
    agent_keyword_hit_rate?: number;
    rag_latency_ms?: (number | null);
    agent_latency_ms?: (number | null);
    rag_sources_count?: number;
    agent_sources_count?: number;
    agent_tool_call_count?: number;
    agent_failed_tool_count?: number;
    agent_tool_names?: Array<(string)>;
    rag_error_message?: (string | null);
    agent_error_message?: (string | null);
    rag_answer?: (string | null);
    agent_answer?: (string | null);
    created_at?: (string | null);
};

export type RagAgentCompareFailureReasonStat = {
    reason: string;
    reason_label: string;
    count?: number;
};

export type RagAgentCompareFileReportResponse = {
    filename: string;
    mime_type: string;
    content_base64: string;
};

export type RagAgentCompareItemPublic = {
    id: string;
    batch_id: string;
    knowledge_base_id: string;
    owner_id: string;
    eval_case_id?: (string | null);
    question: string;
    expected_keywords?: Array<(string)>;
    expected_source_filename?: (string | null);
    rag_answer?: (string | null);
    agent_answer?: (string | null);
    rag_latency_ms?: (number | null);
    agent_latency_ms?: (number | null);
    rag_sources_count?: number;
    agent_sources_count?: number;
    agent_tool_call_count?: number;
    agent_failed_tool_count?: number;
    agent_tool_names?: Array<(string)>;
    rag_sources?: Array<RagChatSource>;
    agent_sources?: Array<RagChatSource>;
    agent_tool_calls?: Array<AgentToolCallPublic>;
    rag_trace?: Array<(string)>;
    agent_trace?: Array<(string)>;
    rag_error_message?: (string | null);
    agent_error_message?: (string | null);
    is_failed?: boolean;
    created_at?: (string | null);
};

export type RagAgentCompareReportResponse = {
    filename: string;
    content: string;
};

export type RagChatRequest = {
    question: string;
    top_k?: number;
    semantic_weight?: number;
    keyword_weight?: number;
};

export type RagChatResponse = {
    answer: string;
    sources: Array<RagChatSource>;
    trace: Array<(string)>;
    run_id?: (string | null);
    latency_ms?: (number | null);
};

export type RagChatSource = {
    document_id: string;
    original_filename: string;
    chunk_id: string;
    chunk_index: number;
    content: string;
    content_length: number;
    match_count?: number;
    similarity?: (number | null);
    retrieval_type?: string;
};

export type RagEvalBatchesPublic = {
    data: Array<RagEvalBatchPublic>;
    count: number;
};

export type RagEvalBatchPublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    name: string;
    note?: (string | null);
    top_k: number;
    semantic_weight: number;
    keyword_weight: number;
    total_cases: number;
    ran: number;
    failed: number;
    average_score?: (number | null);
    keyword_hit_rate?: (number | null);
    source_hit_rate?: (number | null);
    average_latency_ms?: (number | null);
    created_at?: (string | null);
};

export type RagEvalBatchRunRequest = {
    top_k?: number;
    limit?: number;
    semantic_weight?: number;
    keyword_weight?: number;
    batch_name?: (string | null);
    batch_note?: (string | null);
};

export type RagEvalBatchRunResult = {
    total_cases: number;
    ran: number;
    failed: number;
    top_k: number;
    semantic_weight: number;
    keyword_weight: number;
    average_score?: (number | null);
    keyword_hit_rate?: (number | null);
    source_hit_rate?: (number | null);
    average_latency_ms?: (number | null);
};

export type RagEvalCaseCreate = {
    question: string;
    expected_keywords?: Array<(string)>;
    expected_source_filename?: (string | null);
    note?: (string | null);
};

export type RagEvalCasePublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    question: string;
    expected_keywords?: Array<(string)>;
    expected_source_filename?: (string | null);
    note?: (string | null);
    created_at?: (string | null);
};

export type RagEvalCasesPublic = {
    data: Array<RagEvalCasePublic>;
    count: number;
};

export type RagEvalFailureAnalysis = {
    total_runs: number;
    failed_runs: number;
    failure_rate?: (number | null);
    keyword_miss_count: number;
    source_miss_count: number;
    error_count: number;
    low_score_count: number;
    zero_score_count: number;
    average_failed_latency_ms?: (number | null);
    recent_failed_runs?: Array<RagEvalRunPublic>;
};

export type RagEvalParamGroup = {
    top_k: number;
    semantic_weight: number;
    keyword_weight: number;
    preset_names?: Array<(string)>;
    total_runs: number;
    average_score?: (number | null);
    keyword_hit_rate?: (number | null);
    source_hit_rate?: (number | null);
    failure_rate?: (number | null);
    average_latency_ms?: (number | null);
    latest_run_at?: (string | null);
};

export type RagEvalParamGroups = {
    data: Array<RagEvalParamGroup>;
    count: number;
};

export type RagEvalRunPublic = {
    id: string;
    eval_case_id: string;
    knowledge_base_id: string;
    owner_id: string;
    question: string;
    answer: string;
    expected_keywords?: Array<(string)>;
    expected_source_filename?: (string | null);
    sources?: Array<RagChatSource>;
    trace?: Array<(string)>;
    keyword_hit?: (boolean | null);
    source_hit?: (boolean | null);
    score?: (number | null);
    retrieval_type: string;
    top_k?: number;
    semantic_weight?: number;
    keyword_weight?: number;
    latency_ms?: (number | null);
    error_message?: (string | null);
    created_at?: (string | null);
    is_failed?: boolean;
    failure_reasons?: Array<(string)>;
};

export type RagEvalRunRequest = {
    top_k?: number;
    semantic_weight?: number;
    keyword_weight?: number;
};

export type RagEvalRunsPublic = {
    data: Array<RagEvalRunPublic>;
    count: number;
};

export type RagEvalSummary = {
    total_runs: number;
    average_score?: (number | null);
    keyword_hit_rate?: (number | null);
    source_hit_rate?: (number | null);
    average_latency_ms?: (number | null);
    max_score?: (number | null);
    min_score?: (number | null);
    latest_run_at?: (string | null);
};

export type RagRetrievalPresetCreate = {
    name: string;
    top_k?: number;
    semantic_weight?: number;
    keyword_weight?: number;
    note?: (string | null);
};

export type RagRetrievalPresetPublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    name: string;
    top_k: number;
    semantic_weight: number;
    keyword_weight: number;
    note?: (string | null);
    created_at?: (string | null);
};

export type RagRetrievalPresetsPublic = {
    data: Array<RagRetrievalPresetPublic>;
    count: number;
};

export type RagRunPublic = {
    id: string;
    knowledge_base_id: string;
    owner_id: string;
    question: string;
    answer: string;
    retrieval_type: string;
    top_k?: number;
    semantic_weight?: number;
    keyword_weight?: number;
    latency_ms?: (number | null);
    sources?: Array<RagChatSource>;
    trace?: Array<(string)>;
    error_message?: (string | null);
    created_at?: (string | null);
};

export type RagRunsPublic = {
    data: Array<RagRunPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ParseCodeSkillDiffData = {
    requestBody: CodeSkillParseDiffRequest;
};

export type ParseCodeSkillDiffResponse = (CodeSkillParseDiffResponse);

export type LocateCodeSkillChangedSymbolsData = {
    knowledgeBaseId: string;
    requestBody: CodeSkillLocateChangedSymbolsRequest;
};

export type LocateCodeSkillChangedSymbolsResponse = (CodeSkillLocateChangedSymbolsResponse);

export type FindCodeSkillImpactsData = {
    knowledgeBaseId: string;
    requestBody: CodeSkillFindImpactsRequest;
};

export type FindCodeSkillImpactsResponse = (CodeSkillFindImpactsResponse);

export type RecommendCodeSkillTestsData = {
    knowledgeBaseId: string;
    requestBody: CodeSkillRecommendTestsRequest;
};

export type RecommendCodeSkillTestsResponse = (CodeSkillRecommendTestsResponse);

export type BuildCodeSkillReviewEvidenceData = {
    knowledgeBaseId: string;
    requestBody: CodeSkillBuildReviewEvidenceRequest;
};

export type BuildCodeSkillReviewEvidenceResponse = (CodeSkillReviewEvidenceResponse);

export type ResolveCodeReviewSourceData = {
    knowledgeBaseId: string;
    requestBody: CodeReviewSourceResolveRequest;
};

export type ResolveCodeReviewSourceResponse = (CodeReviewSourceResolvedPublic);

export type GenerateCodeSkillReviewReportData = {
    knowledgeBaseId: string;
    requestBody: CodeSkillGenerateReviewReportRequest;
};

export type GenerateCodeSkillReviewReportResponse = (CodeSkillGenerateReviewReportResponse);

export type ReadCodeReviewRunsData = {
    generationStatus?: ('completed' | 'evidence_only' | null);
    knowledgeBaseId: string;
    /**
     * 单页返回数量，最大 100
     */
    limit?: number;
    riskLevel?: ('low' | 'medium' | 'high' | null);
    /**
     * 跳过的历史记录数量
     */
    skip?: number;
};

export type ReadCodeReviewRunsResponse = (CodeReviewRunsPublic);

export type CompareCodeReviewRunsData = {
    knowledgeBaseId: string;
    requestBody: CodeReviewCompareRequest;
};

export type CompareCodeReviewRunsResponse = (CodeReviewCompareResponse);

export type ReadCodeReviewRunDetailData = {
    knowledgeBaseId: string;
    reviewRunId: string;
};

export type ReadCodeReviewRunDetailResponse = (CodeReviewRunDetailPublic);

export type DeleteCodeReviewRunData = {
    knowledgeBaseId: string;
    reviewRunId: string;
};

export type DeleteCodeReviewRunResponse = (Message);

export type PreviewGithubCodeReviewPublicationData = {
    knowledgeBaseId: string;
    reviewRunId: string;
};

export type PreviewGithubCodeReviewPublicationResponse = (GitHubReviewPublicationPreviewPublic);

export type PublishGithubCodeReviewData = {
    knowledgeBaseId: string;
    requestBody: GitHubReviewPublicationRequest;
    reviewRunId: string;
};

export type PublishGithubCodeReviewResponse = (GitHubReviewPublicationResultPublic);

export type ReadCodeReviewPublicationsData = {
    knowledgeBaseId: string;
    reviewRunId: string;
};

export type ReadCodeReviewPublicationsResponse = (CodeReviewPublicationsPublic);

export type DocumentsDownloadDocumentData = {
    documentId: string;
};

export type DocumentsDownloadDocumentResponse = (unknown);

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
    knowledgeBaseId: string;
};

export type DocumentsUploadDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentsByKnowledgeBaseData = {
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentsByKnowledgeBaseResponse = (DocumentsPublic);

export type UploadCodeRepositoryZipData = {
    formData: Body_upload_code_repository_zip;
    knowledgeBaseId: string;
};

export type UploadCodeRepositoryZipResponse = (DocumentsPublic);

export type DocumentsReadDocumentChunksData = {
    documentId: string;
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentChunksResponse = (DocumentChunksPublic);

export type DocumentsSearchKnowledgeBaseChunksData = {
    knowledgeBaseId: string;
    requestBody: KnowledgeBaseSearchRequest;
};

export type DocumentsSearchKnowledgeBaseChunksResponse = (KnowledgeBaseSearchResults);

export type SemanticSearchKnowledgeBaseChunksData = {
    knowledgeBaseId: string;
    requestBody: KnowledgeBaseSemanticSearchRequest;
};

export type SemanticSearchKnowledgeBaseChunksResponse = (KnowledgeBaseSemanticSearchResults);

export type ChatWithKnowledgeBaseData = {
    knowledgeBaseId: string;
    requestBody: RagChatRequest;
};

export type ChatWithKnowledgeBaseResponse = (RagChatResponse);

export type AgentChatWithKnowledgeBaseData = {
    knowledgeBaseId: string;
    requestBody: AgentChatRequest;
};

export type AgentChatWithKnowledgeBaseResponse = (AgentChatResponse);

export type ReadAgentRunsData = {
    keyword?: (string | null);
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type ReadAgentRunsResponse = (AgentRunsPublic);

export type DeleteAgentRunData = {
    agentRunId: string;
};

export type DeleteAgentRunResponse = (Message);

export type ReadKnowledgeBaseAgentSettingsData = {
    knowledgeBaseId: string;
};

export type ReadKnowledgeBaseAgentSettingsResponse = (KnowledgeBaseAgentSettingsPublic);

export type UpdateKnowledgeBaseAgentSettingsData = {
    knowledgeBaseId: string;
    requestBody: KnowledgeBaseAgentSettingsUpdate;
};

export type UpdateKnowledgeBaseAgentSettingsResponse = (KnowledgeBaseAgentSettingsPublic);

export type ReadKnowledgeBaseRagRunsData = {
    keyword?: (string | null);
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type ReadKnowledgeBaseRagRunsResponse = (RagRunsPublic);

export type DeleteRagRunData = {
    ragRunId: string;
};

export type DeleteRagRunResponse = (Message);

export type BackfillKnowledgeBaseEmbeddingsData = {
    knowledgeBaseId: string;
    requestBody: KnowledgeBaseEmbeddingBackfillRequest;
};

export type BackfillKnowledgeBaseEmbeddingsResponse = (KnowledgeBaseEmbeddingBackfillResult);

export type CreateRagEvalCaseData = {
    knowledgeBaseId: string;
    requestBody: RagEvalCaseCreate;
};

export type CreateRagEvalCaseResponse = (RagEvalCasePublic);

export type ReadRagEvalCasesData = {
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type ReadRagEvalCasesResponse = (RagEvalCasesPublic);

export type SeedCodeEvalCasesData = {
    knowledgeBaseId: string;
    maxFiles?: number;
    maxSymbols?: number;
};

export type SeedCodeEvalCasesResponse = (RagEvalCasesPublic);

export type GetCodeEvalTypeCompareSummaryData = {
    knowledgeBaseId: string;
};

export type GetCodeEvalTypeCompareSummaryResponse = (CodeEvalTypeCompareSummaryPublic);

export type ReadRagAgentCompareFailureAnalysisData = {
    batchId?: (string | null);
    caseType?: (string | null);
    knowledgeBaseId: string;
    limit?: number;
};

export type ReadRagAgentCompareFailureAnalysisResponse = (RagAgentCompareFailureAnalysisPublic);

export type DeleteRagEvalCaseData = {
    evalCaseId: string;
};

export type DeleteRagEvalCaseResponse = (Message);

export type RunRagEvalCaseData = {
    evalCaseId: string;
    requestBody: RagEvalRunRequest;
};

export type RunRagEvalCaseResponse = (RagEvalRunPublic);

export type CreateRagRetrievalPresetData = {
    knowledgeBaseId: string;
    requestBody: RagRetrievalPresetCreate;
};

export type CreateRagRetrievalPresetResponse = (RagRetrievalPresetPublic);

export type ReadRagRetrievalPresetsData = {
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type ReadRagRetrievalPresetsResponse = (RagRetrievalPresetsPublic);

export type DeleteRagRetrievalPresetData = {
    presetId: string;
};

export type DeleteRagRetrievalPresetResponse = (Message);

export type RunRagAgentCompareEvalData = {
    knowledgeBaseId: string;
    requestBody: RagAgentCompareEvalRequest;
};

export type RunRagAgentCompareEvalResponse = (RagAgentCompareEvalResponse);

export type ReadRagAgentCompareBatchesData = {
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type ReadRagAgentCompareBatchesResponse = (RagAgentCompareBatchesPublic);

export type ReadRagAgentCompareBatchData = {
    batchId: string;
};

export type ReadRagAgentCompareBatchResponse = (RagAgentCompareBatchDetailPublic);

export type DeleteRagAgentCompareBatchData = {
    batchId: string;
};

export type DeleteRagAgentCompareBatchResponse = (Message);

export type ReadCodeAgentExperimentReportData = {
    baselineBatchId: string;
    failureLimit?: number;
    knowledgeBaseId: string;
    optimizedBatchId: string;
};

export type ReadCodeAgentExperimentReportResponse = (CodeAgentExperimentReportPublic);

export type ReadRagAgentCompareBatchReportData = {
    batchId: string;
};

export type ReadRagAgentCompareBatchReportResponse = (RagAgentCompareReportResponse);

export type ReadRagAgentCompareBatchDocxReportData = {
    batchId: string;
};

export type ReadRagAgentCompareBatchDocxReportResponse = (RagAgentCompareFileReportResponse);

export type ReadRagAgentCompareBatchPdfReportData = {
    batchId: string;
};

export type ReadRagAgentCompareBatchPdfReportResponse = (RagAgentCompareFileReportResponse);

export type RunAllRagEvalCasesData = {
    knowledgeBaseId: string;
    requestBody: RagEvalBatchRunRequest;
};

export type RunAllRagEvalCasesResponse = (RagEvalBatchRunResult);

export type ReadRagEvalBatchesData = {
    knowledgeBaseId: string;
    limit?: number;
    skip?: number;
};

export type ReadRagEvalBatchesResponse = (RagEvalBatchesPublic);

export type DeleteRagEvalBatchData = {
    batchId: string;
};

export type DeleteRagEvalBatchResponse = (Message);

export type ReadRagEvalSummaryData = {
    knowledgeBaseId: string;
    limit?: number;
};

export type ReadRagEvalSummaryResponse = (RagEvalSummary);

export type ReadRagEvalRunsData = {
    errorOnly?: boolean;
    failedOnly?: boolean;
    keyword?: (string | null);
    keywordHit?: (boolean | null);
    knowledgeBaseId: string;
    limit?: number;
    maxScore?: (number | null);
    minScore?: (number | null);
    skip?: number;
    sourceHit?: (boolean | null);
};

export type ReadRagEvalRunsResponse = (RagEvalRunsPublic);

export type ReadRagEvalFailureAnalysisData = {
    knowledgeBaseId: string;
    limit?: number;
    recentLimit?: number;
};

export type ReadRagEvalFailureAnalysisResponse = (RagEvalFailureAnalysis);

export type ReadRagEvalParamGroupsData = {
    knowledgeBaseId: string;
    limit?: number;
};

export type ReadRagEvalParamGroupsResponse = (RagEvalParamGroups);

export type DocumentsReadDocumentData = {
    documentId: string;
};

export type DocumentsReadDocumentResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    documentId: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type KnowledgeBasesReadKnowledgeBasesData = {
    limit?: number;
    skip?: number;
};

export type KnowledgeBasesReadKnowledgeBasesResponse = (KnowledgeBasesPublic);

export type KnowledgeBasesCreateKnowledgeBaseData = {
    requestBody: KnowledgeBaseCreate;
};

export type KnowledgeBasesCreateKnowledgeBaseResponse = (KnowledgeBasePublic);

export type KnowledgeBasesReadKnowledgeBaseData = {
    id: string;
};

export type KnowledgeBasesReadKnowledgeBaseResponse = (KnowledgeBasePublic);

export type KnowledgeBasesUpdateKnowledgeBaseData = {
    id: string;
    requestBody: KnowledgeBaseUpdate;
};

export type KnowledgeBasesUpdateKnowledgeBaseResponse = (KnowledgeBasePublic);

export type KnowledgeBasesDeleteKnowledgeBaseData = {
    id: string;
};

export type KnowledgeBasesDeleteKnowledgeBaseResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);