"""add rag agent compare batches

Revision ID: 0128829d1589
Revises: a4e02d95d159
Create Date: 2026-07-08 08:04:24.320309

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0128829d1589'
down_revision = 'a4e02d95d159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_agent_compare_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('semantic_weight', sa.Float(), nullable=False),
    sa.Column('keyword_weight', sa.Float(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('ran', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('average_rag_latency_ms', sa.Float(), nullable=True),
    sa.Column('average_agent_latency_ms', sa.Float(), nullable=True),
    sa.Column('average_rag_sources_count', sa.Float(), nullable=True),
    sa.Column('average_agent_sources_count', sa.Float(), nullable=True),
    sa.Column('average_agent_tool_call_count', sa.Float(), nullable=True),
    sa.Column('total_agent_failed_tool_count', sa.Integer(), nullable=False),
    sa.Column('summarize_document_count', sa.Integer(), nullable=False),
    sa.Column('read_document_chunks_count', sa.Integer(), nullable=False),
    sa.Column('search_rag_history_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_agent_compare_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('eval_case_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_keywords_json', sa.Text(), nullable=False),
    sa.Column('expected_source_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('rag_answer', sa.Text(), nullable=True),
    sa.Column('agent_answer', sa.Text(), nullable=True),
    sa.Column('rag_latency_ms', sa.Integer(), nullable=True),
    sa.Column('agent_latency_ms', sa.Integer(), nullable=True),
    sa.Column('rag_sources_count', sa.Integer(), nullable=False),
    sa.Column('agent_sources_count', sa.Integer(), nullable=False),
    sa.Column('agent_tool_call_count', sa.Integer(), nullable=False),
    sa.Column('agent_failed_tool_count', sa.Integer(), nullable=False),
    sa.Column('agent_tool_names_json', sa.Text(), nullable=False),
    sa.Column('rag_sources_json', sa.Text(), nullable=False),
    sa.Column('agent_sources_json', sa.Text(), nullable=False),
    sa.Column('agent_tool_calls_json', sa.Text(), nullable=False),
    sa.Column('rag_trace_json', sa.Text(), nullable=False),
    sa.Column('agent_trace_json', sa.Text(), nullable=False),
    sa.Column('rag_error_message', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('agent_error_message', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['rag_agent_compare_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_agent_compare_item')
    op.drop_table('rag_agent_compare_batch')
    # ### end Alembic commands ###
