"""add code review publications

Revision ID: 27b171258eb3
Revises: 2d7947174406
Create Date: 2026-07-16 07:25:05.815232

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '27b171258eb3'
down_revision = '2d7947174406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_review_publication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('review_run_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('publication_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('requested_event', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_repository', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('target_change_number', sa.Integer(), nullable=False),
    sa.Column('target_head_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('force_republish', sa.Boolean(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('body_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('external_review_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('external_review_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('external_review_state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('external_actor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('github')", name='ck_code_review_publication_provider'),
    sa.CheckConstraint("publication_type IN ('pull_request_review')", name='ck_code_review_publication_type'),
    sa.CheckConstraint("requested_event IN ('COMMENT', 'APPROVE', 'REQUEST_CHANGES')", name='ck_code_review_publication_event'),
    sa.CheckConstraint("status IN ('publishing', 'succeeded', 'failed')", name='ck_code_review_publication_status'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_code_review_publication_attempt_positive'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_run_id'], ['code_review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_run_id', 'attempt_number', name='uq_code_review_publication_run_attempt')
    )
    op.create_index('ix_code_review_publication_knowledge_base_created_at', 'code_review_publication', ['knowledge_base_id', 'created_at'], unique=False)
    op.create_index('ix_code_review_publication_owner_created_at', 'code_review_publication', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_code_review_publication_run_created_at', 'code_review_publication', ['review_run_id', 'created_at'], unique=False)
    op.create_index('ix_code_review_publication_run_status', 'code_review_publication', ['review_run_id', 'status'], unique=False)
    op.create_index('uq_code_review_publication_active_attempt', 'code_review_publication', ['review_run_id'], unique=True, postgresql_where=sa.text("status = 'publishing'"))
    op.create_index('uq_code_review_publication_external_review', 'code_review_publication', ['provider', 'external_review_id'], unique=True, postgresql_where=sa.text('external_review_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_code_review_publication_external_review', table_name='code_review_publication', postgresql_where=sa.text('external_review_id IS NOT NULL'))
    op.drop_index('uq_code_review_publication_active_attempt', table_name='code_review_publication', postgresql_where=sa.text("status = 'publishing'"))
    op.drop_index('ix_code_review_publication_run_status', table_name='code_review_publication')
    op.drop_index('ix_code_review_publication_run_created_at', table_name='code_review_publication')
    op.drop_index('ix_code_review_publication_owner_created_at', table_name='code_review_publication')
    op.drop_index('ix_code_review_publication_knowledge_base_created_at', table_name='code_review_publication')
    op.drop_table('code_review_publication')
    # ### end Alembic commands ###
