"""add chunk embeddings

Revision ID: 29aab29adcfc
Revises: d150a029652b
Create Date: 2026-07-04 08:56:02.987392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '29aab29adcfc'
down_revision = 'd150a029652b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunk', sa.Column('embedding', sa.Text(), nullable=True))
    op.add_column('document_chunk', sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column(
        'document_chunk',
        sa.Column(
            'embedding_status',
            sa.String(length=50),
            nullable=False,
            server_default='pending',
        ),
    )
    op.alter_column('document_chunk', 'embedding_status', server_default=None)
    op.add_column('document_chunk', sa.Column('embedding_error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunk', 'embedding_error')
    op.drop_column('document_chunk', 'embedding_status')
    op.drop_column('document_chunk', 'embedding_model')
    op.drop_column('document_chunk', 'embedding')
    # ### end Alembic commands ###
