"""add code review source snapshot fields

Revision ID: 2d7947174406
Revises: cbd3b5393db8
Create Date: 2026-07-15 13:14:26.414268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d7947174406'
down_revision = 'cbd3b5393db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_review_run', sa.Column('source_diff_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.alter_column('code_review_run', 'source_fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_review_run', 'source_fetched_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('code_review_run', 'source_diff_hash')
    # ### end Alembic commands ###
