"""add code review run history

Revision ID: 382ae04e7780
Revises: ea52d868b9fe
Create Date: 2026-07-13 12:01:30.312805

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '382ae04e7780'
down_revision = 'ea52d868b9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_review_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('diff_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('generation_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('merge_recommendation', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('changed_file_count', sa.Integer(), nullable=False),
    sa.Column('changed_symbol_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('recommended_test_count', sa.Integer(), nullable=False),
    sa.Column('request_parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_markdown', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_review_run_created_at'), 'code_review_run', ['created_at'], unique=False)
    op.create_index(op.f('ix_code_review_run_diff_hash'), 'code_review_run', ['diff_hash'], unique=False)
    op.create_index(op.f('ix_code_review_run_generation_status'), 'code_review_run', ['generation_status'], unique=False)
    op.create_index('ix_code_review_run_knowledge_base_created_at', 'code_review_run', ['knowledge_base_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_code_review_run_knowledge_base_id'), 'code_review_run', ['knowledge_base_id'], unique=False)
    op.create_index('ix_code_review_run_knowledge_base_risk', 'code_review_run', ['knowledge_base_id', 'risk_level'], unique=False)
    op.create_index('ix_code_review_run_knowledge_base_status', 'code_review_run', ['knowledge_base_id', 'generation_status'], unique=False)
    op.create_index('ix_code_review_run_owner_created_at', 'code_review_run', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_code_review_run_owner_id'), 'code_review_run', ['owner_id'], unique=False)
    op.create_index(op.f('ix_code_review_run_risk_level'), 'code_review_run', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_review_run_risk_level'), table_name='code_review_run')
    op.drop_index(op.f('ix_code_review_run_owner_id'), table_name='code_review_run')
    op.drop_index('ix_code_review_run_owner_created_at', table_name='code_review_run')
    op.drop_index('ix_code_review_run_knowledge_base_status', table_name='code_review_run')
    op.drop_index('ix_code_review_run_knowledge_base_risk', table_name='code_review_run')
    op.drop_index(op.f('ix_code_review_run_knowledge_base_id'), table_name='code_review_run')
    op.drop_index('ix_code_review_run_knowledge_base_created_at', table_name='code_review_run')
    op.drop_index(op.f('ix_code_review_run_generation_status'), table_name='code_review_run')
    op.drop_index(op.f('ix_code_review_run_diff_hash'), table_name='code_review_run')
    op.drop_index(op.f('ix_code_review_run_created_at'), table_name='code_review_run')
    op.drop_table('code_review_run')
    # ### end Alembic commands ###
