"""add repository analysis leases

Revision ID: 708a1bd4a5f5
Revises: 91fb819f86c3
Create Date: 2026-07-22 08:55:50.265991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '708a1bd4a5f5'
down_revision = '91fb819f86c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_analysis_task', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.add_column('repository_analysis_task', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('repository_analysis_task', sa.Column('next_attempt_at', sa.DateTime(), nullable=True))
    op.add_column('repository_analysis_task', sa.Column('last_recovery_reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.alter_column('repository_analysis_task', 'heartbeat_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_repository_analysis_task_heartbeat_at'), 'repository_analysis_task', ['heartbeat_at'], unique=False)
    op.create_index(op.f('ix_repository_analysis_task_lease_expires_at'), 'repository_analysis_task', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_repository_analysis_task_next_attempt_at'), 'repository_analysis_task', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_analysis_task_next_attempt_at'), table_name='repository_analysis_task')
    op.drop_index(op.f('ix_repository_analysis_task_lease_expires_at'), table_name='repository_analysis_task')
    op.drop_index(op.f('ix_repository_analysis_task_heartbeat_at'), table_name='repository_analysis_task')
    op.alter_column('repository_analysis_task', 'heartbeat_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('repository_analysis_task', 'last_recovery_reason')
    op.drop_column('repository_analysis_task', 'next_attempt_at')
    op.drop_column('repository_analysis_task', 'max_attempts')
    op.drop_column('repository_analysis_task', 'lease_expires_at')
    # ### end Alembic commands ###
