"""add rag agent compare batches

Revision ID: 7d8d141e01a4
Revises: 0128829d1589
Create Date: 2026-07-08 08:14:28.910570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d8d141e01a4'
down_revision = '0128829d1589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
