"""add repository analysis task

Revision ID: 91fb819f86c3
Revises: 27b171258eb3
Create Date: 2026-07-17 06:01:34.991060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91fb819f86c3'
down_revision = '27b171258eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_analysis_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('repository_owner', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('repository_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('repository_full_name', sqlmodel.sql.sqltypes.AutoString(length=356), nullable=False),
    sa.Column('requested_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('resolved_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('analysis_mode', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('report_language', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('snapshot_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('snapshot_storage_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'expired')", name='ck_repository_analysis_task_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_repository_analysis_task_attempt_count'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_repository_analysis_task_progress'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_analysis_task_expires_at'), 'repository_analysis_task', ['expires_at'], unique=False)
    op.create_index(op.f('ix_repository_analysis_task_knowledge_base_id'), 'repository_analysis_task', ['knowledge_base_id'], unique=False)
    op.create_index('ix_repository_analysis_task_owner_created', 'repository_analysis_task', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_repository_analysis_task_owner_id'), 'repository_analysis_task', ['owner_id'], unique=False)
    op.create_index('ix_repository_analysis_task_queue', 'repository_analysis_task', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_repository_analysis_task_repository_full_name'), 'repository_analysis_task', ['repository_full_name'], unique=False)
    op.create_index(op.f('ix_repository_analysis_task_status'), 'repository_analysis_task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_analysis_task_status'), table_name='repository_analysis_task')
    op.drop_index(op.f('ix_repository_analysis_task_repository_full_name'), table_name='repository_analysis_task')
    op.drop_index('ix_repository_analysis_task_queue', table_name='repository_analysis_task')
    op.drop_index(op.f('ix_repository_analysis_task_owner_id'), table_name='repository_analysis_task')
    op.drop_index('ix_repository_analysis_task_owner_created', table_name='repository_analysis_task')
    op.drop_index(op.f('ix_repository_analysis_task_knowledge_base_id'), table_name='repository_analysis_task')
    op.drop_index(op.f('ix_repository_analysis_task_expires_at'), table_name='repository_analysis_task')
    op.drop_table('repository_analysis_task')
    # ### end Alembic commands ###
