"""add repository scope to chat runs

Revision ID: b849b5521d03
Revises: c87fbaa45f91
Create Date: 2026-07-27 02:28:28.120603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b849b5521d03'
down_revision = 'c87fbaa45f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_run', sa.Column('repository_analysis_task_id', sa.Uuid(), nullable=True))
    op.add_column('agent_run', sa.Column('source_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_agent_run_repository_analysis_task_id'), 'agent_run', ['repository_analysis_task_id'], unique=False)
    op.create_foreign_key(None, 'agent_run', 'repository_analysis_task', ['repository_analysis_task_id'], ['id'], ondelete='SET NULL')
    op.add_column('rag_run', sa.Column('repository_analysis_task_id', sa.Uuid(), nullable=True))
    op.add_column('rag_run', sa.Column('source_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_rag_run_repository_analysis_task_id'), 'rag_run', ['repository_analysis_task_id'], unique=False)
    op.create_foreign_key(None, 'rag_run', 'repository_analysis_task', ['repository_analysis_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rag_run', type_='foreignkey')
    op.drop_index(op.f('ix_rag_run_repository_analysis_task_id'), table_name='rag_run')
    op.drop_column('rag_run', 'source_commit_sha')
    op.drop_column('rag_run', 'repository_analysis_task_id')
    op.drop_constraint(None, 'agent_run', type_='foreignkey')
    op.drop_index(op.f('ix_agent_run_repository_analysis_task_id'), table_name='agent_run')
    op.drop_column('agent_run', 'source_commit_sha')
    op.drop_column('agent_run', 'repository_analysis_task_id')
    # ### end Alembic commands ###
