"""add repository import metadata

Revision ID: c87fbaa45f91
Revises: ede18f5f2499
Create Date: 2026-07-25 03:33:26.778663

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c87fbaa45f91'
down_revision = 'ede18f5f2499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('repository_analysis_task_id', sa.Uuid(), nullable=True))
    op.add_column('document', sa.Column('repository_relative_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    op.add_column('document', sa.Column('source_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_document_repository_analysis_task_id'), 'document', ['repository_analysis_task_id'], unique=False)
    op.create_index(op.f('ix_document_source_commit_sha'), 'document', ['source_commit_sha'], unique=False)
    op.create_foreign_key(None, 'document', 'repository_analysis_task', ['repository_analysis_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_source_commit_sha'), table_name='document')
    op.drop_index(op.f('ix_document_repository_analysis_task_id'), table_name='document')
    op.drop_column('document', 'source_commit_sha')
    op.drop_column('document', 'repository_relative_path')
    op.drop_column('document', 'repository_analysis_task_id')
    # ### end Alembic commands ###
