"""add rag retrieval presets

Revision ID: cd2538011e3d
Revises: bfa66ba12a7b
Create Date: 2026-07-07 03:44:36.668618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd2538011e3d'
down_revision = 'bfa66ba12a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_retrieval_preset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('semantic_weight', sa.Float(), nullable=False),
    sa.Column('keyword_weight', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_retrieval_preset')
    # ### end Alembic commands ###
