"""add knowledge base agent settings

Revision ID: ea52d868b9fe
Revises: 7d8d141e01a4
Create Date: 2026-07-08 11:55:41.136979

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea52d868b9fe'
down_revision = '7d8d141e01a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_agent_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('semantic_weight', sa.Float(), nullable=False),
    sa.Column('keyword_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_agent_settings_knowledge_base_id'), 'knowledge_base_agent_settings', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_agent_settings_owner_id'), 'knowledge_base_agent_settings', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_agent_settings_owner_id'), table_name='knowledge_base_agent_settings')
    op.drop_index(op.f('ix_knowledge_base_agent_settings_knowledge_base_id'), table_name='knowledge_base_agent_settings')
    op.drop_table('knowledge_base_agent_settings')
    # ### end Alembic commands ###
