"""add repository analysis task lease fields

Revision ID: ede18f5f2499
Revises: 708a1bd4a5f5
Create Date: 2026-07-24 06:41:23.980375

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ede18f5f2499'
down_revision = '708a1bd4a5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
