/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutKnowledgeBasesRouteImport } from './routes/_layout/knowledge-bases'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as Layout3RouteImport } from './routes/_layout/3'
import { Route as Layout2RouteImport } from './routes/_layout/2'
import { Route as Layout1RouteImport } from './routes/_layout/1'
import { Route as LayoutKnowledgeBasesIndexRouteImport } from './routes/_layout/knowledge-bases.index'
import { Route as LayoutKnowledgeBasesKnowledgeBaseIdRouteImport } from './routes/_layout/knowledge-bases.$knowledgeBaseId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBasesRoute = LayoutKnowledgeBasesRouteImport.update({
  id: '/knowledge-bases',
  path: '/knowledge-bases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const Layout3Route = Layout3RouteImport.update({
  id: '/3',
  path: '/3',
  getParentRoute: () => LayoutRoute,
} as any)
const Layout2Route = Layout2RouteImport.update({
  id: '/2',
  path: '/2',
  getParentRoute: () => LayoutRoute,
} as any)
const Layout1Route = Layout1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBasesIndexRoute =
  LayoutKnowledgeBasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutKnowledgeBasesRoute,
  } as any)
const LayoutKnowledgeBasesKnowledgeBaseIdRoute =
  LayoutKnowledgeBasesKnowledgeBaseIdRouteImport.update({
    id: '/$knowledgeBaseId',
    path: '/$knowledgeBaseId',
    getParentRoute: () => LayoutKnowledgeBasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/1': typeof Layout1Route
  '/2': typeof Layout2Route
  '/3': typeof Layout3Route
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/knowledge-bases': typeof LayoutKnowledgeBasesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/knowledge-bases/$knowledgeBaseId': typeof LayoutKnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-bases/': typeof LayoutKnowledgeBasesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/1': typeof Layout1Route
  '/2': typeof Layout2Route
  '/3': typeof Layout3Route
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/knowledge-bases/$knowledgeBaseId': typeof LayoutKnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-bases': typeof LayoutKnowledgeBasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/1': typeof Layout1Route
  '/_layout/2': typeof Layout2Route
  '/_layout/3': typeof Layout3Route
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/knowledge-bases': typeof LayoutKnowledgeBasesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/knowledge-bases/$knowledgeBaseId': typeof LayoutKnowledgeBasesKnowledgeBaseIdRoute
  '/_layout/knowledge-bases/': typeof LayoutKnowledgeBasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/1'
    | '/2'
    | '/3'
    | '/admin'
    | '/items'
    | '/knowledge-bases'
    | '/settings'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-bases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/1'
    | '/2'
    | '/3'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-bases'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/1'
    | '/_layout/2'
    | '/_layout/3'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/knowledge-bases'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/knowledge-bases/$knowledgeBaseId'
    | '/_layout/knowledge-bases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-bases': {
      id: '/_layout/knowledge-bases'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases'
      preLoaderRoute: typeof LayoutKnowledgeBasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/3': {
      id: '/_layout/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof Layout3RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/2': {
      id: '/_layout/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof Layout2RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/1': {
      id: '/_layout/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof Layout1RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-bases/': {
      id: '/_layout/knowledge-bases/'
      path: '/'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof LayoutKnowledgeBasesIndexRouteImport
      parentRoute: typeof LayoutKnowledgeBasesRoute
    }
    '/_layout/knowledge-bases/$knowledgeBaseId': {
      id: '/_layout/knowledge-bases/$knowledgeBaseId'
      path: '/$knowledgeBaseId'
      fullPath: '/knowledge-bases/$knowledgeBaseId'
      preLoaderRoute: typeof LayoutKnowledgeBasesKnowledgeBaseIdRouteImport
      parentRoute: typeof LayoutKnowledgeBasesRoute
    }
  }
}

interface LayoutKnowledgeBasesRouteChildren {
  LayoutKnowledgeBasesKnowledgeBaseIdRoute: typeof LayoutKnowledgeBasesKnowledgeBaseIdRoute
  LayoutKnowledgeBasesIndexRoute: typeof LayoutKnowledgeBasesIndexRoute
}

const LayoutKnowledgeBasesRouteChildren: LayoutKnowledgeBasesRouteChildren = {
  LayoutKnowledgeBasesKnowledgeBaseIdRoute:
    LayoutKnowledgeBasesKnowledgeBaseIdRoute,
  LayoutKnowledgeBasesIndexRoute: LayoutKnowledgeBasesIndexRoute,
}

const LayoutKnowledgeBasesRouteWithChildren =
  LayoutKnowledgeBasesRoute._addFileChildren(LayoutKnowledgeBasesRouteChildren)

interface LayoutRouteChildren {
  Layout1Route: typeof Layout1Route
  Layout2Route: typeof Layout2Route
  Layout3Route: typeof Layout3Route
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKnowledgeBasesRoute: typeof LayoutKnowledgeBasesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  Layout1Route: Layout1Route,
  Layout2Route: Layout2Route,
  Layout3Route: Layout3Route,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKnowledgeBasesRoute: LayoutKnowledgeBasesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
